# Generated by Django 4.0.1 on 2022-01-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_vaccinated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vaccinated_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
